[general]
log_level = "info"
debounce_seconds = 2
polling_interval_secs = 5
log_retention = 1000
start_daemon_on_launch = false
notifications_enabled = false
theme = "catppuccin-mocha"

[[watch]]
path = "~/Downloads"
recursive = false
rules = []

[[rule]]
name = "Move iso files"
enabled = true
stop_processing = false

[rule.condition]
extension = "iso"
extensions = []
is_directory = false

[rule.action]
type = "move"
destination = "~/Downloads/iso"
create_destination = true
overwrite = false
