# -------------------------------------------
# chpwd Hook - Run Commands on Directory Change
# -------------------------------------------
# NOTE: Only one chpwd hook can be defined at once
# To merge them, use add-zsh-hook which is mentioned below
autoload -Uz add-zsh-hook

# Then Define separate functions
function auto_venv() {
  # If already in a virtualenv, do nothing
  if [[ -n "$VIRTUAL_ENV" && "$PWD" != *"${VIRTUAL_ENV:h}"* ]]; then
    deactivate
    return  
  fi

  [[ -n "$VIRTUAL_ENV" ]] && return

  local dir="$PWD"
  while [[ "$dir" != "/" ]]; do
    if [[ -f "$dir/.venv/bin/activate" ]]; then
      source "$dir/.venv/bin/activate"
      return
    fi
    dir="${dir:h}"
  done
}

function auto_nix() {
  # If we're already in a nix develop shell, do nothing
  [[ -n "$IN_NIX_SHELL" ]] && return

  # Walk up to find a flake
  local dir="$PWD"
  while [[ "$dir" != "/" ]]; do
    if [[ -f "$dir/flake.nix" ]]; then
      # If this project already has .envrc, just allow it (you can remove this if you prefer)
      if [[ ! -f "$dir/.envrc" ]]; then
        # Create .envrc that loads the dev env (fast, no interactive shell)
        cat > "$dir/.envrc" <<'EOF'
# autogenerated: load flake dev environment
eval "$(nix print-dev-env)"
EOF
        command direnv allow "$dir" >/dev/null 2>&1
      fi

      command direnv reload >/dev/null 2>&1
      return
    fi
    dir="${dir:h}"
  done
}

function auto_nvm() {
  [[ -f .nvmrc ]] && nvm use
}

# Register them all
add-zsh-hook chpwd auto_venv
add-zsh-hook chpwd auto_nix
add-zsh-hook chpwd auto_nvm
